#!/bin/bash

function register {
	read -p "이름: " name
	
	if [ -z $name ]; then
		echo "이름을 입력하지 않았습니다. 아무 키나 누르세요..."
		return
	fi
	
	for ele in $(cat phonebook | grep -w $name); do
		if [ $name = $ele ]; then
	  	echo "이미 존재하는 이름입니다 아무키나 누르세요..."
			return
		fi
	done
	read -p "전화번호: " number

	echo $name $number >> phonebook

	echo "등록되었습니다. 아무 키나 누르세요..."
}

function search {	
	read -p "이름: " s_name	
		
	if [ -z $s_name ]; then
		echo "이름을 입력하지 않았습니다. 아무 키나 누르세요..."
		return
	fi

	for ele in $(cat phonebook | grep -w $s_name); do
		if [ $s_name = $ele ]; then
			echo $(cat phonebook | grep -w $s_name)
			echo "아무 키나 누르세요..."
			return
		fi
	done

	echo "그런 이름은 없습니다. 아무 키나 누르세요..."
}

function delete {
	read -p "이름: " d_name
	
	if [ -z $d_name ]; then
		echo "이름을 입력하지 않았습니다. 아무 키나 누르세요..."
		return
	fi


	for ele in $(cat phonebook | grep -w $d_name); do
		if [ $d_name = $ele ]; then
			sed -i "/$ele/d" phonebook
			echo "삭제되었습니다. 아무 키나 누르세요..."
			return
		else
			echo "그런 이름은 없습니다. 아무 키나 누르세요..."
			return
		fi
	done
}

touch phonebook
while true;
do
	clear
	echo "1. 등록"
	echo "2. 검색"
	echo "3. 삭제"
	read -p "입력(0. 종료): "

	case $REPLY in
	1) register
	read
	;;
#exit;;
	2) search
	read
	;;
#exit;;
	3) delete
	read
	;;
#exit;;
	0) exit;;
#exit;;
	esac
done

