services:
  app:
    build: 
      context: .
    ports:
      - ":5000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - "80:80"